language: python

dist: trusty

branches:
  only:
    - /.*/

sudo: false

addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
  chrome: stable

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - nvm install lts/*

install:
 - export RESPEC_RELEASE="v20.0.3"
 - make travissetup

script:
 - make check
