language: python
python:
  - "2.7_with_system_site_packages"
sudo: false
addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
      - python-lxml
install:
 - git clone https://github.com/w3c/webrtc-respec-ci.git
 - make -f webrtc-respec-ci/Makefile travissetup
script:
 - make -f webrtc-respec-ci/Makefile check
