language: python
python:
  - "2.7_with_system_site_packages"
sudo: false
addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
      - python-lxml
install:
 - git clone https://github.com/dontcallmedom/respec-ci.git
 - make -f respec-ci/Makefile travissetup
script:
 - make -f respec-ci/Makefile check
